replicaCount: 1

image:
  repository: ghcr.io/immadhav7/livequiz-app
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: livequiz.local

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    memory: 1Gi

database:
  image: mysql:8.4
  name: livequiz
  user: livequiz
  existingSecret: livequiz-db
  storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      memory: 768Mi
